export const MENSAJE_TITULO = {
    CAMPO_OBLIGATORIO : 'Este campo es obligatorio *',
    NOMBRE_ACTIVIDAD_ESTRATEGICA : 'Nombre de la actividad estratégica - PAT',
    NOMBRE_PROGRAMA : 'Nombre del programa ó PAT',
    NOMBRE_GESTION_AREA : 'Nombre de la gestión del área',
    NOMBRE_PROYECTO_AREA : 'Nombre del proyecto del área',
    NOMBRE_PROYECTO : 'Nombre del proyecto',
    NOMBRE_ACTIVIDAD_GESTION : 'Nombre de la actividad de gestión',
    NOMBRE_SPRINT_PROYECTO : 'Nombre del sprint del proyecto',
    NOMBRE_SPRINT_PROYECTO_AREA : 'Nombre del sprint del proyecto del área',
    NOMBRE_TAREA_DE_GESTION_AREA : 'Nombre de la tarea de la gestión el área',
    NOMBRE_TAREA_SPRINT_PROYECTO : 'Nombre de la tarea del sprint del proyecto',
    NOMBRE_TAREA_SPRINT_PROYECTO_AREA : 'Nombre de la tarea del sprint del proyecto del área',
    NOMBRE_TAREA_ACTVIDAD_GESTION : 'Nombre de la tarea de la actividad de gestión',
    FECHA_ANUAL_PAT : 'Año en que se ejecuta el programa',
    FECHA_INICIAL_ACTIVIDAD_ESTRATEGICA : 'Fecha inicial de la actividad estratégica',
    FECHA_INICIAL_ACTIVIDAD_GESTION : 'Fecha inicial de la actividad de gestión',
    FECHA_INICIAL_GESTION_AREA : 'Fecha inicial de la gestión del área',
    FECHA_INICIAL_SPRINT_PROYECTO : 'Fecha inicial del sprint del proyecto',
    FECHA_INICIAL_SPRINT_PROYECTO_AREA : 'Fecha inicial del sprint del proyecto del área',
    FECHA_INICIAL_PROYECTO_AREA : 'Fecha inicial del proyecto del área',
    FECHA_INICIAL_PROYECTO : 'Fecha inicial del proyecto',
    FECHA_FINAL_ACTIVIDAD_ESTRATEGICA : 'Fecha final de la actividad estratégica',
    FECHA_FINAL_ACTIVIDAD_GESTION : 'Fecha final de la actividad de gestión',
    FECHA_FINAL_GESTION_AREA : 'Fecha final de la gestión del área',
    FECHA_FINAL_SPRINT_PROYECTO : 'Fecha final del sprint del proyecto',
    FECHA_FINAL_SPRINT_PROYECTO_AREA : 'Fecha final del sprint del proyecto del área',
    FECHA_FINAL_PROYECTO_AREA : 'Fecha final del proyecto del área',
    FECHA_FINAL_PROYECTO : 'Fecha final del proyecto',
    DURACION : 'Diferencia de días entre la fecha inicial y fecha final',
    DIAS_RESTANTES : 'Diferencia de días calendario desde la fecha actual a la fecha final',
    AVANCE_REAL_PAT :'Promedio actual del porcentaje real de las actividades estratégicas - PAT, gestiones del área y proyectos del área',
    AVANCE_REAL_ACTIVIDAD_ESTRATEGICA : 'Promedio actual del porcentaje real de los proyectos y actividades internas',
    AVANCE_REAL_ACTIVIDAD_GESTION : 'Promedio actual del porcentaje de las tareas internas',
    AVANCE_REAL_TAREA : 'Porcentaje real de la tarea',
    AVANCE_REAL_SPRINT : 'Promedio actual del porcentaje real de las tareas intenas',
    AVANCE_REAL_PROYECTO : 'Promedio actual del porcentaje real de los sprint del proyecto',
    AVANCE_REAL_PROYECTO_AREA : 'Promedio actual del porcentaje real de los sprint del proyecto del área',
    AVANCE_ESPERADO : 'Difrencia entre fecha inicial y la fecha actual, dividido la duración (Días)',
    AVANCE_PAT : 'Promedio del total de actividades estratégicas - PAT internas sobre la suma del % PAT de ellas',
    CUMPLIMIENTO : 'Division entre el % Avance real y % Avance esperado',
    DIRECCION : 'Dirección relacionada al programa',
    ACCIONES : 'Acciones',
    RESPONSABLE_PAT : 'Colaborador responsable del programa',
    RESPONSABLE_ACTIVIDAD_ESTRATEGICA : 'Colaborador responsable de la actividad estratégica - PAT',
    RESPONSABLE_GESTION_AREA : 'Colaborador responsable de la gestión el área',
    RESPONSABLE_PROYECTO_AREA : 'Colaborador responsable del proyecto del área',
    RESPONSABLE_PROYECTO : 'Colaborador responsable del proyecto',
    RESPONSABLE_ACTIVIDAD_GESTION : 'Colaborador responsable de la actividad gestión',
    RESPONSABLE_SPRINT : 'Colaborador responsable del sprint',
    RESPONSABLE_SPRINT_PROYECTO_AREA : 'Colaborador responsable del sprint del proyecto del área',
    RESPONSABLE_TAREA : 'Colaborador responsable de la tarea',
    META_KPI : 'Meta ponderada al inicio de la actividad estratégica',
    RESULTADO_META_KPI : 'Valor digitado a medida que se va avanzando en la Meta (KPI)',
    PROMEDIO_META_KPI : 'División entre Resultado Meta (KPI) y Meta (KPI)',
    ENTREGABLE : 'Entregable digitado por el usuario',
    PORCENTAJE_PAT :'La suma de: % Cumplimiento multiplicado por 40% y % Meta (KPI) multiplicado por 60%',
    PERIODICIDAD_TAREA : 'Periodicidad de la tarea',
    ESTADO_TAREA : 'Estado actual de la tarea, en backlog(Sin comienzo), en proceso(En gestión), terminado(Finalizado) y impedimento(Sin terminar)',
    DESCRIPCION_TAREA : 'Descripción de la tarea',
    PRESUPUESTO_PROYECTO : 'Presupuesto de la de proyecto',
    PRESUPUESTO_PROYECTO_AREA : 'Presupuesto de la de proyecto del área',
    MODALIDAD_PROYECTO : 'Modalidad en que se ejeucta el proyecto',
    MODALIDAD_PROYECTO_AREA : 'Modalidad en que se ejeucta el proyecto del área',
    VALOR_EJECUTADO_PROYECTO : 'Valor en que se ejeucta el proyecto',
    VALOR_EJECUTADO_PROYECTO_AREA : 'Valor en que se ejeucta el proyecto del área',
    PLANEACION_PROYECTO : 'Tiempo en que se define los sprint del proyecto',
    PLANEACION_PROYECTO_AREA : 'Tiempo en que se define los sprint del proyecto del área',
    TOTAL_SPRINT_PROYECTO : 'Número de sprints del proyecto',
    TOTAL_SPRINT_PROYECTO_AREA : 'Número de sprints del proyecto del área',

  };