export const MENSAJE_TITULO = {
    NOMBRE_ACTIVIDAD_ESTRATEGICA : 'Nombre de la actividad estratégica - PAT',
    NOMBRE_PROGRAMA : 'Nombre del programa ó PAT',
    NOMBRE_GESTION_AREA : 'Nombre de la gestión del área',
    NOMBRE_PROYECTO_AREA : 'Nombre del proyecto del área',
    NOMBRE_PROYECTO : 'Nombre del proyecto',
    NOMBRE_ACTIVIDAD_GESTION : 'Nombre de la actividad de gestión',
    NOMBRE_SPRINT_PROYECTO : 'Nombre del sprint del proyecto',
    NOMBRE_SPRINT_PROYECTO_AREA : 'Nombre del sprint del proyecto del área',
    NOMBRE_TAREA_DE_GESTION_AREA : 'Nombre de la tarea de la actividad el área',
    NOMBRE_TAREA_SPRINT_PROYECTO : 'Nombre de la tarea del sprint del proyecto',
    NOMBRE_TAREA_SPRINT_PROYECTO_AREA : 'Nombre de la tarea del sprint del proyecto del área',
    NOMBRE_TAREA_DE_ACTVIDAD_GESTION : 'Nombre de la tarea de la actividad de gestión',
    FECHA_INICIAL_ACTIVIDAD_ESTRATEGICA : 'Fecha inicial de la actividad estratégica',
    FECHA_INICIAL_ACTIVIDAD_GESTION : 'Fecha inicial de la actividad de gestión',
    FECHA_INICIAL_GESTION_AREA : 'Fecha inicial de la gestión del área',
    FECHA_INICIAL_SPRINT_PROYECTO : 'Fecha inicial del sprint del proyecto',
    FECHA_INICIAL_SPRINT_PROYECTO_AREA : 'Fecha inicial del sprint del proyecto del área',
    FECHA_INICIAL_PROYECTO_AREA : 'Fecha inicial del proyecto del área',
    FECHA_INICIAL_PROYECTO : 'Fecha inicial del proyecto',
    FECHA_FINAL_ACTIVIDAD_ESTRATEGICA : 'Fecha final de la actividad estratégica',
    FECHA_FINAL_ACTIVIDAD_GESTION : 'Fecha final de la actividad de gestión',
    FECHA_FINAL_GESTION_AREA : 'Fecha final de la gestión del área',
    FECHA_FINAL_SPRINT_PROYECTO : 'Fecha final del sprint del proyecto',
    FECHA_FINAL_SPRINT_PROYECTO_AREA : 'Fecha final del sprint del proyecto del área',
    FECHA_FINAL_PROYECTO_AREA : 'Fecha final del proyecto del área',
    FECHA_FINAL_PROYECTO : 'Fecha final del proyecto',
    DURACION : 'Diferencia de días entre la fecha inicial y fecha final',
    DIAS_RESTANTES : 'Diferencia de días desde la fecha actual a la fecha final',
    AVANCE_REAL_ACTIVIDAD_ESTRATEGICA : 'Promedio actual del porcentaje real de los proyectos y actividades internas',
    AVANCE_REAL : 'Promedio actual del porcentaje real de las tareas internas',
    AVANCE_REAL_PROYECTO : 'Promedio actual del porcentaje real de los sprint del proyecto',
    AVANCE_REAL_PROYECTO_AREA : 'Promedio actual del porcentaje real de los sprint del proyecto del área',
    AVANCE_ESPERADO : 'Difrencia entre fecha inicial y la fecha actual, dividido la duración (Días)',
    CUMPLIMIENTO : 'Division entre el % Avance real y % Avance esperado',
    ACCIONES : 'Acciones',
  };