export enum EPeriodicidad {
    UNICA_VEZ =  'UNICA_VEZ',
    SEMANAL = 'SEMANAL',
    QUINCENAL = 'QUINCENAL',
    MENSUAL = 'MENSUAL',
    BIMESTRAL = 'BIMESTRAL',
    TRIMESTRAL = 'TRIMESTRAL',
    SEMESTRAL = 'SEMESTRAL',
    ANUAL = 'ANUAL'
}